server:
  port: 8080

spring:
  application:
    name: @project.artifactId@  # The name of the service, taking the artifactId in pom.xml
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB # A single file is the largest
      max-request-size: 100MB # The maximum size of requests received
  cloud:
    nacos: # The stand-alone version disables the capabilities of Nacos service discovery and configuration management
      config:
        enabled: false
      discovery:
        enabled: false
  main:
    allow-bean-definition-overriding: true # Allows overriding of bean definitions
  profiles:
    active: dev


# Swagger configuration
swagger:
  token-url: ${swagger.gateway}/admin/oauth2/token